// ndds_unicode_table.h

#ifndef _NDDS_UNICODE_TABLE_H
#define _NDDS_UNICODE_TABLE_H

#define NDDS_UCS2_TO_KSSM_CHO_TABLE_SIZE			19
#define NDDS_UCS2_TO_KSSM_JUNG_TABLE_SIZE		21
#define NDDS_KSC5601_TO_UCS2_TABLE_SIZE			8742

extern unsigned short	NDDS_UCS2_TO_KSSM_CHO_TABLE[NDDS_UCS2_TO_KSSM_CHO_TABLE_SIZE];
extern unsigned short	NDDS_UCS2_TO_KSSM_JUNG_TABLE[NDDS_UCS2_TO_KSSM_JUNG_TABLE_SIZE];
//extern unsigned short	NDDS_KSC5601_TO_UCS2_TABLE[NDDS_KSC5601_TO_UCS2_TABLE_SIZE];
extern int NDDS_KSC5601_TO_UCS2_TABLE[NDDS_KSC5601_TO_UCS2_TABLE_SIZE];

#endif
