// ndds_hancode_table.h

#ifndef __NDDS_HANCODE_TABLE_H
#define __NDDS_HANCODE_TABLE_H

#define NDDS_HANCODE_SINGLE_TABLE_SIZE		51
#define NDDS_HANCODE_TABLE_SIZE				2350

extern unsigned short NDDS_HANCODE_SINGLE_TABLE[NDDS_HANCODE_SINGLE_TABLE_SIZE];
extern unsigned short NDDS_HANCODE_TABLE[NDDS_HANCODE_TABLE_SIZE];

#endif // __NDDS_HANCODE_TABLE_H
