/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a navigationserviceadaptor -i navigationservicetype.h NavigationService_qdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIGATIONSERVICEADAPTOR_H_1485233139
#define NAVIGATIONSERVICEADAPTOR_H_1485233139

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "navigationservicetype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE


class NavigationServer;

/*
 * Adaptor class for interface org.bosch.cm.navigation.NavigationService
 */
class NavigationServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bosch.cm.navigation.NavigationService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bosch.cm.navigation.NavigationService\">\n"
"    <property access=\"read\" type=\"u\" name=\"navStatus\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"datasetVersion\"/>\n"
"    <property access=\"read\" type=\"((dd)dssuddissssss)\" name=\"positionInformation\">\n"
"      <annotation value=\"NSPositionInformation\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(suu)\" name=\"distanceToDestination\">\n"
"      <annotation value=\"NSDistanceToDestination\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"s\" name=\"currentStreet\"/>\n"
"    <property access=\"read\" type=\"(us)\" name=\"turntoStreet\">\n"
"      <annotation value=\"NSTurnToStreet\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"q\" name=\"roundaboutExitNumber\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"nextTurntoStreet\"/>\n"
"    <property access=\"read\" type=\"(bqquss)\" name=\"barGraphInfo\">\n"
"      <annotation value=\"NSBarGraphInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"maneuverSymbol\"/>\n"
"    <property access=\"read\" type=\"(yyysqy(dd))\" name=\"satelliteInfo\">\n"
"      <annotation value=\"NSSatelliteInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"a((dd)sss)\" name=\"destinationInformation\">\n"
"      <annotation value=\"NSDestinationInfoElements\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"readwrite\" type=\"(uu)\" name=\"routeCalculationDuration\">\n"
"      <annotation value=\"NSRouteCalculationDuration\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(s(dd)b)\" name=\"homeLocation\">\n"
"      <annotation value=\"NSHomeLocation\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(s(dd)b)\" name=\"workLocation\">\n"
"      <annotation value=\"NSWorkLocation\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"mapRepresentation\"/>\n"
"    <property access=\"read\" type=\"(a(us(b))(bbbbbb)au)\" name=\"sdsAddressWithOptions\">\n"
"      <annotation value=\"NSSDSAddressWithOptions\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"a((dd)us)\" name=\"waypointList\">\n"
"      <annotation value=\"NSWaypointList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(uu(buu))\" name=\"maneuverView\">\n"
"      <annotation value=\"NSManeuverView\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(bsqu)\" name=\"speedLimit\">\n"
"      <annotation value=\"NSSpeedLimit\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"readwrite\" type=\"(uusuuu)\" name=\"trafficEnforcement\">\n"
"      <annotation value=\"NSTrafficEnforcement\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(suubb)\" name=\"nextManeuverDetails\">\n"
"      <annotation value=\"NSNextManeuverDetails\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"a(uii)\" name=\"laneRecommendationList\">\n"
"      <annotation value=\"NSLaneRecommendationList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"a((suu)sisiiuuui)\" name=\"arrivalInformationList\">\n"
"      <annotation value=\"NSArrivalInformationList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"b\" name=\"isAddressBookChanged\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"isLastDestinationListChanged\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"isVoiceGuidanceActive\"/>\n"
"    <property access=\"read\" type=\"a(su(ayu)y((nin)ub))\" name=\"menuPoiCategoryShortcuts\">\n"
"      <annotation value=\"NSPoiCategoryShortcuts\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"b\" name=\"OverSpeedSoundAlertInfoActive\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"routeRecalculationReason\"/>\n"
"    <property access=\"read\" type=\"au\" name=\"waypointOperationStatusList\">\n"
"      <annotation value=\"NSWaypointOpertaionStatusList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"destinationReachedStatus\"/>\n"
"    <property access=\"read\" type=\"(uu)\" name=\"mapVideoStreamStatus\">\n"
"      <annotation value=\"NSMapVideoStreamResult\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <method name=\"selectPoiCategoryShortcut\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"shortcutIndex\"/>\n"
"    </method>\n"
"    <method name=\"getNavDataPartNumber\">\n"
"      <arg direction=\"out\" type=\"(us)\" name=\"navDataPartNumber\"/>\n"
"      <annotation value=\"NSNavDataPartNumber\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"getPoiCategoryShortcuts\">\n"
"      <arg direction=\"out\" type=\"a(su(ayu)y((nin)ub))\" name=\"poiCategoryShortcuts\"/>\n"
"      <annotation value=\"NSPoiCategoryShortcuts\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"setLocationWithCoordinates\">\n"
"      <arg direction=\"in\" type=\"(dd)\" name=\"location\"/>\n"
"      <annotation value=\"NSPositionWGS84\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"setLocationWithDetails\">\n"
"      <arg direction=\"in\" type=\"((s(dd)b)ss(ayu))\" name=\"location\"/>\n"
"      <annotation value=\"NSPOILocation\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"showPOILocationFromTCU\">\n"
"      <arg direction=\"in\" type=\"a((s(dd)b)ss(ayu))\" name=\"poiLocations\"/>\n"
"      <annotation value=\"NSPOILocations\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"storePOILocationToAddressBook\">\n"
"      <arg direction=\"in\" type=\"((s(dd)b)ss(ayu))\" name=\"poiLocation\"/>\n"
"      <annotation value=\"NSPOILocation\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"storeLocationToAddressBook\">\n"
"      <arg direction=\"in\" type=\"(s(dd)b)\" name=\"location\"/>\n"
"      <annotation value=\"NSLocation\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"showCalculateTour\">\n"
"      <arg direction=\"in\" type=\"a(((s(dd)b)ss(ayu))bu)\" name=\"tour\"/>\n"
"      <annotation value=\"NSTour\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"screenTransition\"/>\n"
"    </method>\n"
"    <method name=\"showOnMap\">\n"
"      <arg direction=\"in\" type=\"(dd)\" name=\"location\"/>\n"
"      <annotation value=\"NSPositionWGS84\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"showCarsorLocationOnMap\">\n"
"    </method>\n"
"    <method name=\"showAdjustCurrentLocationScreen\">\n"
"    </method>\n"
"    <method name=\"showWhereAmIScreen\">\n"
"    </method>\n"
"    <method name=\"showDeleteWaypointListScreen\">\n"
"    </method>\n"
"    <method name=\"setZoomInStep\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"zoomInStep\"/>\n"
"    </method>\n"
"    <method name=\"setZoomOutStep\">\n"
"      <arg direction=\"in\" type=\"y\" name=\"zoomOutStep\"/>\n"
"    </method>\n"
"    <method name=\"setZoomLevel\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"zoomLevel\"/>\n"
"    </method>\n"
"    <method name=\"getVersionString\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"versionString\"/>\n"
"    </method>\n"
"    <method name=\"startGuidance\">\n"
"    </method>\n"
"    <method name=\"startGuidanceToPosWGS84\">\n"
"      <arg direction=\"in\" type=\"(dd)\" name=\"destination\"/>\n"
"      <annotation value=\"NSPositionWGS84\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"startGuidanceToHomeLocation\">\n"
"    </method>\n"
"    <method name=\"startGuidanceToWorkLocation\">\n"
"    </method>\n"
"    <method name=\"setLocationWithDestinationMemoryEntry\">\n"
"      <arg direction=\"in\" type=\"t\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"cancelRouteGuidance\">\n"
"    </method>\n"
"    <method name=\"insertWaypoint\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"newIndex\"/>\n"
"    </method>\n"
"    <method name=\"insertWaypointAtDefaultPosition\">\n"
"    </method>\n"
"    <method name=\"replaceWaypoint\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"index\"/>\n"
"    </method>\n"
"    <method name=\"deleteWaypoints\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"firstIndex\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"lastIndex\"/>\n"
"    </method>\n"
"    <method name=\"applyWaypointListChange\">\n"
"    </method>\n"
"    <method name=\"requestWaypointList\">\n"
"    </method>\n"
"    <method name=\"requestFreeTextSearchResults\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"searchString\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"searchScope\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"destinationIndex\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"startIndex\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"numElements\"/>\n"
"      <arg direction=\"out\" type=\"a(stssu(dd)((nin)ub))\" name=\"searchResults\"/>\n"
"      <annotation value=\"NSAddressWithIdInfos\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"undoFreeTextSearchElementSelection\">\n"
"    </method>\n"
"    <method name=\"setLocationWithFreeTextSearchInput\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"showDestinationFreeTextSearchInput\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"locationType\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"locationSearchScope\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"searchString\"/>\n"
"    </method>\n"
"    <method name=\"sdsCheckAddress\">\n"
"      <arg direction=\"in\" type=\"a(us(b))\" name=\"requestedAddress\"/>\n"
"      <annotation value=\"NSSDSAddress\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sdsGetRefinementList\">\n"
"      <arg direction=\"out\" type=\"a(susu)\" name=\"refinements\"/>\n"
"      <annotation value=\"NSRefinementWithIdInfos\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"selectSdsRefinement\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"setLocationWithSdsInput\">\n"
"    </method>\n"
"    <method name=\"requestDestinationMemoryEntries\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"categoryType\"/>\n"
"      <arg direction=\"out\" type=\"a((stu)(sssssssssssa(sus))(dd))\" name=\"destinationMemoryEntries\"/>\n"
"      <annotation value=\"NSDestinationMemoryDetailsList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"setMapRepresentation\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"representation\"/>\n"
"    </method>\n"
"    <method name=\"requestDetailsForSelectedLocation\">\n"
"      <arg direction=\"out\" type=\"(sssssssss(dd))\" name=\"locationDetail\"/>\n"
"      <annotation value=\"NSLocationDetails\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"retriggerAcousticOutput\">\n"
"    </method>\n"
"    <method name=\"speakSamplePhrase\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"sampleVoicePhrase\"/>\n"
"    </method>\n"
"    <method name=\"setRouteCriterion\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"routeCriterion\"/>\n"
"    </method>\n"
"    <method name=\"setVoiceGuidance\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"active\"/>\n"
"    </method>\n"
"    <method name=\"sdsGetHouseNumberPattern\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"minHouseNumber\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"maxHouseNumber\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"patterns\"/>\n"
"    </method>\n"
"    <method name=\"showLocationSelectionAndGetAddressDetails\">\n"
"      <arg direction=\"out\" type=\"((stu)(sssssssssssa(sus))(dd))\" name=\"destinationMemoryDetailListElement\"/>\n"
"      <annotation value=\"NSDestinationMemoryDetailListElement\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"showAndSetLocationWithDetails\">\n"
"      <arg direction=\"in\" type=\"((s(dd)b)ss(ayu))\" name=\"location\"/>\n"
"      <annotation value=\"NSPOILocation\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"navigationVersion\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"navigationCoreVersion\"/>\n"
"    </method>\n"
"    <method name=\"startMapVideoStream\">\n"
"      <arg direction=\"in\" type=\"(uu)\" name=\"mapVideoStreamDimensions\"/>\n"
"      <annotation value=\"NSMapVideoStreamDimensions\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"ipAddress\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"portnumber\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"videoType\"/>\n"
"      <arg direction=\"out\" type=\"(uu)\" name=\"mapVideoStreamResult\"/>\n"
"      <annotation value=\"NSMapVideoStreamResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"modifyMapVideoStream\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"mapVideoStreamHandle\"/>\n"
"      <arg direction=\"in\" type=\"(uu)\" name=\"mapVideoStreamDimensions\"/>\n"
"      <annotation value=\"NSMapVideoStreamDimensions\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"q\" name=\"videoType\"/>\n"
"      <arg direction=\"out\" type=\"(uu)\" name=\"mapVideoStreamResult\"/>\n"
"      <annotation value=\"NSMapVideoStreamResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"deleteMapVideoStream\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"mapVideoStreamHandle\"/>\n"
"      <arg direction=\"out\" type=\"(uu)\" name=\"mapVideoStreamResult\"/>\n"
"      <annotation value=\"NSMapVideoStreamResult\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NavigationServiceAdaptor(NavigationServer *parent);
    virtual ~NavigationServiceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool OverSpeedSoundAlertInfoActive READ OverSpeedSoundAlertInfoActive)
    bool OverSpeedSoundAlertInfoActive() const;

    Q_PROPERTY(NSArrivalInformationList arrivalInformationList READ arrivalInformationList)
    NSArrivalInformationList arrivalInformationList() const;

    Q_PROPERTY(NSBarGraphInfo barGraphInfo READ barGraphInfo)
    NSBarGraphInfo barGraphInfo() const;

    Q_PROPERTY(QString currentStreet READ currentStreet)
    QString currentStreet() const;

    Q_PROPERTY(QString datasetVersion READ datasetVersion)
    QString datasetVersion() const;

    Q_PROPERTY(NSDestinationInfoElements destinationInformation READ destinationInformation)
    NSDestinationInfoElements destinationInformation() const;

    Q_PROPERTY(uint destinationReachedStatus READ destinationReachedStatus)
    uint destinationReachedStatus() const;

    Q_PROPERTY(NSDistanceToDestination distanceToDestination READ distanceToDestination)
    NSDistanceToDestination distanceToDestination() const;

    Q_PROPERTY(NSHomeLocation homeLocation READ homeLocation)
    NSHomeLocation homeLocation() const;

    Q_PROPERTY(bool isAddressBookChanged READ isAddressBookChanged)
    bool isAddressBookChanged() const;

    Q_PROPERTY(bool isLastDestinationListChanged READ isLastDestinationListChanged)
    bool isLastDestinationListChanged() const;

    Q_PROPERTY(bool isVoiceGuidanceActive READ isVoiceGuidanceActive)
    bool isVoiceGuidanceActive() const;

    Q_PROPERTY(NSLaneRecommendationList laneRecommendationList READ laneRecommendationList)
    NSLaneRecommendationList laneRecommendationList() const;

    Q_PROPERTY(uint maneuverSymbol READ maneuverSymbol)
    uint maneuverSymbol() const;

    Q_PROPERTY(NSManeuverView maneuverView READ maneuverView)
    NSManeuverView maneuverView() const;

    Q_PROPERTY(uint mapRepresentation READ mapRepresentation)
    uint mapRepresentation() const;

    Q_PROPERTY(NSMapVideoStreamResult mapVideoStreamStatus READ mapVideoStreamStatus)
    NSMapVideoStreamResult mapVideoStreamStatus() const;

    Q_PROPERTY(NSPoiCategoryShortcuts menuPoiCategoryShortcuts READ menuPoiCategoryShortcuts)
    NSPoiCategoryShortcuts menuPoiCategoryShortcuts() const;

    Q_PROPERTY(uint navStatus READ navStatus)
    uint navStatus() const;

    Q_PROPERTY(NSNextManeuverDetails nextManeuverDetails READ nextManeuverDetails)
    NSNextManeuverDetails nextManeuverDetails() const;

    Q_PROPERTY(QString nextTurntoStreet READ nextTurntoStreet)
    QString nextTurntoStreet() const;

    Q_PROPERTY(NSPositionInformation positionInformation READ positionInformation)
    NSPositionInformation positionInformation() const;

    Q_PROPERTY(ushort roundaboutExitNumber READ roundaboutExitNumber)
    ushort roundaboutExitNumber() const;

    Q_PROPERTY(NSRouteCalculationDuration routeCalculationDuration READ routeCalculationDuration WRITE setRouteCalculationDuration)
    NSRouteCalculationDuration routeCalculationDuration() const;
    void setRouteCalculationDuration(NSRouteCalculationDuration value);

    Q_PROPERTY(uint routeRecalculationReason READ routeRecalculationReason)
    uint routeRecalculationReason() const;

    Q_PROPERTY(NSSatelliteInfo satelliteInfo READ satelliteInfo)
    NSSatelliteInfo satelliteInfo() const;

    Q_PROPERTY(NSSDSAddressWithOptions sdsAddressWithOptions READ sdsAddressWithOptions)
    NSSDSAddressWithOptions sdsAddressWithOptions() const;

    Q_PROPERTY(NSSpeedLimit speedLimit READ speedLimit)
    NSSpeedLimit speedLimit() const;

    Q_PROPERTY(NSTrafficEnforcement trafficEnforcement READ trafficEnforcement WRITE setTrafficEnforcement)
    NSTrafficEnforcement trafficEnforcement() const;
    void setTrafficEnforcement(NSTrafficEnforcement value);

    Q_PROPERTY(NSTurnToStreet turntoStreet READ turntoStreet)
    NSTurnToStreet turntoStreet() const;

    Q_PROPERTY(NSWaypointList waypointList READ waypointList)
    NSWaypointList waypointList() const;

    Q_PROPERTY(NSWaypointOpertaionStatusList waypointOperationStatusList READ waypointOperationStatusList)
    NSWaypointOpertaionStatusList waypointOperationStatusList() const;

    Q_PROPERTY(NSWorkLocation workLocation READ workLocation)
    NSWorkLocation workLocation() const;

public Q_SLOTS: // METHODS
    void applyWaypointListChange();
    void cancelRouteGuidance();
    NSMapVideoStreamResult deleteMapVideoStream(uint mapVideoStreamHandle);
    void deleteWaypoints(uint firstIndex, uint lastIndex);
    NSNavDataPartNumber getNavDataPartNumber();
    NSPoiCategoryShortcuts getPoiCategoryShortcuts();
    QString getVersionString();
    void insertWaypoint(uint newIndex);
    void insertWaypointAtDefaultPosition();
    NSMapVideoStreamResult modifyMapVideoStream(uint mapVideoStreamHandle, NSMapVideoStreamDimensions mapVideoStreamDimensions, ushort videoType);
    QString navigationVersion();
    void replaceWaypoint(uint index);
    NSDestinationMemoryDetailsList requestDestinationMemoryEntries(uint categoryType);
    NSLocationDetails requestDetailsForSelectedLocation();
    NSAddressWithIdInfos requestFreeTextSearchResults(const QString &searchString, uint searchScope, uchar destinationIndex, uint startIndex, uint numElements);
    void requestWaypointList();
    void retriggerAcousticOutput();
    void sdsCheckAddress(NSSDSAddress requestedAddress);
    QString sdsGetHouseNumberPattern(QString &maxHouseNumber, QStringList &patterns);
    NSRefinementWithIdInfos sdsGetRefinementList();
    void selectPoiCategoryShortcut(uchar shortcutIndex);
    void selectSdsRefinement(uint id);
    void setLocationWithCoordinates(NSPositionWGS84 location);
    void setLocationWithDestinationMemoryEntry(qulonglong id);
    void setLocationWithDetails(NSPOILocation location);
    void setLocationWithFreeTextSearchInput(uint id);
    void setLocationWithSdsInput();
    void setMapRepresentation(uint representation);
    void setRouteCriterion(uint routeCriterion);
    void setVoiceGuidance(bool active);
    void setZoomInStep(uchar zoomInStep);
    void setZoomLevel(uint zoomLevel);
    void setZoomOutStep(uchar zoomOutStep);
    void showAdjustCurrentLocationScreen();
    void showAndSetLocationWithDetails(NSPOILocation location);
    void showCalculateTour(NSTour tour, uint screenTransition);
    void showCarsorLocationOnMap();
    void showDeleteWaypointListScreen();
    void showDestinationFreeTextSearchInput(uint locationType, uint locationSearchScope, const QString &searchString);
    NSDestinationMemoryDetailListElement showLocationSelectionAndGetAddressDetails();
    void showOnMap(NSPositionWGS84 location);
    void showPOILocationFromTCU(NSPOILocations poiLocations);
    void showWhereAmIScreen();
    void speakSamplePhrase(uint sampleVoicePhrase);
    void startGuidance();
    void startGuidanceToHomeLocation();
    void startGuidanceToPosWGS84(NSPositionWGS84 destination);
    void startGuidanceToWorkLocation();
    NSMapVideoStreamResult startMapVideoStream(NSMapVideoStreamDimensions mapVideoStreamDimensions, const QString &ipAddress, ushort portnumber, ushort videoType);
    void storeLocationToAddressBook(NSLocation location);
    void storePOILocationToAddressBook(NSPOILocation poiLocation);
    void undoFreeTextSearchElementSelection();
Q_SIGNALS: // SIGNALS

private:
    NavigationServer* m_Service;
};

#endif
