#!/bin/sh
## only for Qt5.6
export QT_QPA_PLATFORM_PLUGIN_PATH=/opt/Qt5.6.1_dt_es/plugins
export QML2_IMPORT_PATH=/opt/Qt5.6.1_dt_es/qml
# tmap prefix
export RSM2018_PREFIX=/media/njas/DATA0/w0/aivi_tmap_data
RUN_ROOT=/media/njas/DATA0/w0/bin_aivi_tmap
# LD_LIBRARY_PATH 
export LD_LIBRARY_PATH=$RUN_ROOT:$RUN_ROOT/../tmap_rsm2018/mnssdk/lib/linux/debug
# logging filter
export TMAP_LOG_FILTER_DISABLE_STDOUT=0
export TMAP_LOG_FILTER_ENABLE=1
export TMAP_LOG_FILTER_FILEPATH=$RSM2018_PREFIX/tmap_rsm2018/aivi_logging.dlf
# run tmap for rsm2018
$RUN_ROOT/thirdpartynavigation_out.out
