/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c com.bosch.AutomotiveProxy.CarConfiguration -p carconfigurationinterface.h:carconfigurationinterface.cpp com.bosch.AutomotiveProxy.CarConfiguration.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "carconfigurationinterface.h"

/*
 * Implementation of interface class com.bosch.AutomotiveProxy.CarConfiguration
 */

comboschAutomotiveProxyCarConfiguration::comboschAutomotiveProxyCarConfiguration(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

comboschAutomotiveProxyCarConfiguration::~comboschAutomotiveProxyCarConfiguration()
{
}

