/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp NavigationExtService.xml -i navigationexttype.h -p navigationextserviceinterface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "navigationextserviceinterface.h"
using namespace SKT;

/*
 * Implementation of interface class BoschCmProfileInterface
 */

BoschCmProfileInterface::BoschCmProfileInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : TDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

BoschCmProfileInterface::~BoschCmProfileInterface()
{
}

/*
 * Implementation of interface class OrgBoschCmNavigationNavigationExtServiceInterface
 */

OrgBoschCmNavigationNavigationExtServiceInterface::OrgBoschCmNavigationNavigationExtServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : TDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgBoschCmNavigationNavigationExtServiceInterface::~OrgBoschCmNavigationNavigationExtServiceInterface()
{
}

