/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a navigationsdsserviceadaptor -i navigationsdsservicetype.h -i ../server/navigation/navigationservicetype.h NavigationSDSService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIGATIONSDSSERVICEADAPTOR_H
#define NAVIGATIONSDSSERVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "navigationsdsservicetype.h"
#include "../server/navigation/navigationservicetype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

class NavigationSDSService;
/*
 * Adaptor class for interface org.bosch.cm.navigation.NavigationSDSService
 */
class NavigationSDSServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bosch.cm.navigation.NavigationSDSService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bosch.cm.navigation.NavigationSDSService\">\n"
"    <property access=\"read\" type=\"((dd)ssudd)\" name=\"positionStatusInfo\">\n"
"      <annotation value=\"NSPositionStatusInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(ssssss(suq)(suq)(suq)(suq)(suq)(suq)(suq))\" name=\"positionInfo\">\n"
"      <annotation value=\"NSPositionInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(a(us(b))(bbbbbb)au)\" name=\"sdsAddressWithOptions\">\n"
"      <annotation value=\"NSSDSAddressWithOptions\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <method name=\"getMaxWaypointCount\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"maxWayPointCount\"/>\n"
"    </method>\n"
"    <method name=\"sdsCheckAddress\">\n"
"      <arg direction=\"in\" type=\"a(us(b))\" name=\"requestedAddress\"/>\n"
"      <annotation value=\"NSSDSAddress\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sdsGetRefinementList\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"sdsAddressElementType\"/>\n"
"      <arg direction=\"out\" type=\"a(susu)\" name=\"refinements\"/>\n"
"      <annotation value=\"NSRefinementWithIdInfos\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"sdsGetHouseNumberPattern\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"minHouseNumber\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"maxHouseNumber\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"patterns\"/>\n"
"    </method>\n"
"    <method name=\"selectSdsRefinement\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"setLocationWithSdsInput\">\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NavigationSDSServiceAdaptor(NavigationSDSService *parent);
    virtual ~NavigationSDSServiceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(NSPositionInfo positionInfo READ positionInfo)
    NSPositionInfo positionInfo() const;

    Q_PROPERTY(NSPositionStatusInfo positionStatusInfo READ positionStatusInfo)
    NSPositionStatusInfo positionStatusInfo() const;

    Q_PROPERTY(NSSDSAddressWithOptions sdsAddressWithOptions READ sdsAddressWithOptions)
    NSSDSAddressWithOptions sdsAddressWithOptions() const;

public Q_SLOTS: // METHODS
    uint getMaxWaypointCount();
    void sdsCheckAddress(NSSDSAddress requestedAddress);
    QString sdsGetHouseNumberPattern(QString &maxHouseNumber, QStringList &patterns);
    NSRefinementWithIdInfos sdsGetRefinementList(uint sdsAddressElementType);
    void selectSdsRefinement(uint id);
    void setLocationWithSdsInput();
Q_SIGNALS: // SIGNALS

private:
    NavigationSDSService* m_sdsService;
};

#endif
