#include "loggingcategories.h"
#include <QDebug>

IMPLMENT_LOG_HANDLER(sys, "SYS");
IMPLMENT_LOG_HANDLER(ui, "UI");
IMPLMENT_LOG_HANDLER(vsmnavi, "VSMNAVI")
IMPLMENT_LOG_HANDLER(vsmmap, "VSMMAP")
IMPLMENT_LOG_HANDLER(ndds, "NDDS")
IMPLMENT_LOG_HANDLER(localeng, "LOCALENG")
