/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp GuiControl.xml -i guicontroltype.h -p guicontrolinterface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "guicontrolinterface.h"
using namespace SKT;
/*
 * Implementation of interface class BoschGuiCmAiGuicontrolInterface
 */

BoschGuiCmAiGuicontrolInterface::BoschGuiCmAiGuicontrolInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : TDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

BoschGuiCmAiGuicontrolInterface::~BoschGuiCmAiGuicontrolInterface()
{
}

