#ifndef MAPINCLUSTERGMEMTEST_H
#define MAPINCLUSTERGMEMTEST_H

//#define TMAP_CLUSTER_GMEM_TEST_WITH_NO_RENDERER
//#define TMAP_CLUSTER_GMEM_TEST_PAUSE_RENDERER
//#define TMAP_CLUSTER_GMEM_TEST_REDUCE_FBO_SIZE
//#define TMAP_CLUSTER_GMEM_TEST_HIDE_SKYBOX

#endif
