#!/bin/sh
if [ ! $# -gt 0 ]; then
	echo "type method to call and it would need parameter"
	exit
fi

FNC=$1
PARAM=$2
dbus-send --bus=unix:path=/tmp/shared/iddbus/lxcdbus --type=method_call --print-reply --dest=App.Core.AppHmi_Navigation_Ext /com/bosch/cm/ai/navigation/ext org.bosch.cm.navigation.NavigationExtService.$FNC $PARAM
exit
