#!/bin/sh
if [ ! $# -gt 0 ]; then
	echo "type method to call and it would need parameter"
	exit
fi

RPOPERTY=$1
dbus-send --bus=unix:path=/tmp/shared/iddbus/lxcdbus --dest=App.Core.AppHmi_Navigation --print-reply /com/bosch/cm/ai/navigation org.freedesktop.DBus.Properties.Get string:org.bosch.cm.navigation.NavigationService string:$RPOPERTY

