#!/bin/sh
if [ ! $# -gt 1 ]; then
	echo "type method to call and it would need parameters"
	exit
fi

RPOPERTY=$1
PARAM=$2
dbus-send --bus=unix:path=/tmp/shared/iddbus/lxcdbus --dest=App.Core.AppHmi_Navigation --print-reply /com/bosch/cm/ai/navigation org.freedesktop.DBus.Properties.Set string:org.bosch.cm.navigation.NavigationService string:$RPOPERTY variant:$PARAM
