/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp NavigationExtAgent.xml -i extagenttype.h -a NavigationExtAgentAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIGATIONEXTAGENTADAPTOR_H_1502687146
#define NAVIGATIONEXTAGENTADAPTOR_H_1502687146

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "extagenttype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.bosch.cm.navigation.NavigationExtAgent
 */
class NavigationExtAgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bosch.cm.navigation.NavigationExtAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bosch.cm.navigation.NavigationExtAgent\">\n"
"    <signal name=\"position\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"posLatitude\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"posLongitude\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"posSource\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"countryCode\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"countryCodeSource\"/>\n"
"      <arg direction=\"out\" type=\"(iyi)\" name=\"timeZone\"/>\n"
"      <annotation value=\"TimeZoneData\" name=\"org.qtproject.QtDBus.QtTypeName.In5\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"timeZoneSource\"/>\n"
"    </signal>\n"
"    <signal name=\"velocity\">\n"
"      <arg direction=\"out\" type=\"q\" name=\"velocityValue\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"velocitiySource\"/>\n"
"    </signal>\n"
"    <signal name=\"deadreckoning_info\">\n"
"      <arg direction=\"out\" type=\"t\" name=\"drTimestamp\"/>\n"
"      <arg direction=\"out\" type=\"u\" name=\"drSystemTime\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drLatitude\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drLongitude\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drHeading\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drSpeed\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drAltitude\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drTurnrateX\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drTurnrateY\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drTurnrateZ\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drAccelerationX\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drAccelerationY\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"drAccelerationZ\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"drInfoSource\"/>\n"
"      <arg direction=\"out\" type=\"q\" name=\"drInfoValidity\"/>\n"
"    </signal>\n"
"    <signal name=\"mounting\">\n"
"      <arg direction=\"out\" type=\"(yyyyyyyyy)\" name=\"mountAngles\"/>\n"
"      <annotation value=\"MountAngles\" name=\"org.qtproject.QtDBus.QtTypeName.Out5\"/>\n"
"      <arg direction=\"out\" type=\"y\" name=\"mountingSource\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    NavigationExtAgentAdaptor(QObject *parent);
    virtual ~NavigationExtAgentAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void deadreckoning_info(qulonglong drTimestamp, uint drSystemTime, double drLatitude, double drLongitude, double drHeading, double drSpeed, double drAltitude, double drTurnrateX, double drTurnrateY, double drTurnrateZ, double drAccelerationX, double drAccelerationY, double drAccelerationZ, uchar drInfoSource, ushort drInfoValidity);
    void mounting(MountAngles mountAngles, uchar mountingSource);
    void position(double posLatitude, double posLongitude, uchar posSource, ushort countryCode, uchar countryCodeSource, TimeZoneData timeZone, uchar timeZoneSource);
    void velocity(ushort velocityValue, uchar velocitiySource);
};

#endif
