#!/bin/sh
ssh root@172.17.0.1 'rwrfs'
ssh root@172.17.0.1 'find /var/opt/bosch/persistent/certs -type f -name "Fake*" -exec mv {} {}.bck \;'
ssh root@172.17.0.1 'find /var/opt/bosch/persistent/id -type f -name "*" -exec mv {} {}.bck \;' 
ssh root@172.17.0.1 'sync && rorfs'
ssh root@172.17.0.1 'reboot -f'
