#!/bin/sh
su lxc_iddbus
dbus-send --bus=unix:path=/tmp/shared/iddbus/lxcdbus --dest=org.freedesktop.DBus --type=method_call  --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
#dbus-monitor --address unix:path=/tmp/shared/iddbus/lxcdbus
