#!/bin/sh
if [ ! $# -gt 0 ]; then
	echo 'type path to upload'
 	exit
fi
FROM=$1
ssh root@172.17.0.1 'rwrfs'
ssh root@172.17.0.1 'rm -rf /var/opt/bosch/persistent/certs/* && rm -rf /var/opt/bosch/persistent/id/*'
scp -r $FROM/certs root@172.17.0.1:/var/opt/bosch/persistent
scp -r $FROM/id root@172.17.0.1:/var/opt/bosch/persistent
ssh root@172.17.0.1 'sync'
ssh root@172.17.0.1 'rorfs'
ssh root@172.17.0.1 'reboot -f'



