#!/bin/sh
SRC=tmap_rsm2018_nomap
TARGET=tmap_rsm2018_nomap
if [ $# -gt 0 ]; then
	TARGET=$1
	SRC=$1
fi
SRC_PATH=/media/sf_DATA0/w0/$SRC
#mv $TARGET $SRC
rsync -arv --exclude='.git' --exclude='.git*' --exclude='.settings' --exclude='navdata' --exclude='navdata_online' --exclude='static' --exclude='dynamic' --exclude='*.pro.user*' --exclude='.project' --exclude='.cproject' --exclude='*.rcc' $SRC_PATH .
#mv $SRC $TARGET
# --exclude='vsmsdk/build/qtcreator_vsm_sdk/prebuilt' --exclude='mnssdk' --exclude='*.a' --exclude='*.so'
#find $SRC_PATH -not -path "$SRC_PATH/.git*" -not -path "$SRC_PATH/.settings*" -not -path "$SRC_PATH/navdata" -not -path "$SRC_PATH/navdata/*" -not -path "$SRC_PATH/dynamic" -not -path "$SRC_PATH/dynamic/*" -not -path "$SRC_PATH/static" -not -path "$SRC_PATH/static/*" -not -path "$SRC_PATH/.project" -not -path "$SRC_PATH/.cproject" -not -path "$SRC_PATH/*.pro.user*" -exec cp -ruPv '{}' ./tmap_rsm2018 '{}' \;

