/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a navigationdataupdateserviceadaptor -i navigationdataupdateservicetype.h NavigationDataUpdateService.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NAVIGATIONDATAUPDATESERVICEADAPTOR_H
#define NAVIGATIONDATAUPDATESERVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "navigationdataupdateservicetype.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.bosch.cm.navigation.NavigationDataUpdateService
 */
class NavigationDataUpdateServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bosch.cm.navigation.NavigationDataUpdateService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bosch.cm.navigation.NavigationDataUpdateService\">\n"
"    <property access=\"read\" type=\"(uyuss)\" name=\"navigationDataUpdateStatusInfo\">\n"
"      <annotation value=\"NavigationDataUpdateStatusInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"(uyuss)\" name=\"mapDataDeleteStatusInfo\">\n"
"      <annotation value=\"NavigationDataDeleteStatusInfo\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <method name=\"DiagPerformFullUpdateViaUSB\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"ack\"/>\n"
"    </method>\n"
"    <method name=\"DiagPerformFullDeleteMapData\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"ack\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NavigationDataUpdateServiceAdaptor(QObject *parent);
    virtual ~NavigationDataUpdateServiceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(NavigationDataDeleteStatusInfo mapDataDeleteStatusInfo READ mapDataDeleteStatusInfo)
    NavigationDataDeleteStatusInfo mapDataDeleteStatusInfo() const;

    Q_PROPERTY(NavigationDataUpdateStatusInfo navigationDataUpdateStatusInfo READ navigationDataUpdateStatusInfo)
    NavigationDataUpdateStatusInfo navigationDataUpdateStatusInfo() const;

public Q_SLOTS: // METHODS
    uint DiagPerformFullDeleteMapData();
    uint DiagPerformFullUpdateViaUSB();
Q_SIGNALS: // SIGNALS
};

#endif
