#ifndef KEYMAPPING_H
#define KEYMAPPING_H
#define HARDKEYCODE_HK_NAV                              0
#define HARDKEYCODE_HK_DAY_NIGHT                        1
#define HARDKEYCODE_HK_FM_AM                            2
#define HARDKEYCODE_HK_PHONE                            4
#define HARDKEYCODE_HK_SETTINGS                         5
#define HARDKEYCODE_HK_NEXT                             17
#define HARDKEYCODE_HK_PREVIOUS                         18
#define HARDKEYCODE_HK_APP                              19
#define HARDKEYCODE_HK_SOUND                            20
#define HARDKEYCODE_HK_INFO                             22
#define HARDKEYCODE_HK_MAP                              23
#define HARDKEYCODE_HK_ESC                              36
#define HARDKEYCODE_HK_SELECT                           37
#define HARDKEYCODE_HK_DISP                             39
#define HARDKEYCODE_HK_CAMERA                           40
#define HARDKEYCODE_HK_MEDIA                            41
#define HARDKEYCODE_HK_CD                               42
#define HARDKEYCODE_HK_AUX                              43
#define HARDKEYCODE_HK_ILLUM                            44
#define HARDKEYCODE_HK_CAR                              45
#define HARDKEYCODE_HK_MENU                             46
#define HARDKEYCODE_HK_XMTUNER                          47
#define HARDKEYCODE_HK_MUTE                             48
#define HARDKEYCODE_HK_TP                               49
#define HARDKEYCODE_HK_EJECT                            50
#define HARDKEYCODE_HK_POWER                            51
#define HARDKEYCODE_HK_AUDIO                            52
#define HARDKEYCODE_VIRT_SCREENSHOT                     53
#define HARDKEYCODE_VIRT_DISPLAY_OFF                    54
#define HARDKEYCODE_VIRT_TESTMODE                       55
#define HARDKEYCODE_SWC_NEXT                            65
#define HARDKEYCODE_SWC_PREV                            66
#define HARDKEYCODE_SWC_ROTARY_ENCODER_BUTTON           67
#define HARDKEYCODE_SWC_OK                              68
#define HARDKEYCODE_SWC_MENU_BACK                       69
#define HARDKEYCODE_SWC_SWITCH_AUDIO                    70
#define HARDKEYCODE_SWC_MUTE_DEMUTE                     71
#define HARDKEYCODE_SWC_PTT                             72
#define HARDKEYCODE_SWC_PHONE                           73
#define HARDKEYCODE_SWC_MENU                            74
#define HARDKEYCODE_SWC_MENU_UP                         75
#define HARDKEYCODE_SWC_MENU_DOWN                       76
#define HARDKEYCODE_SWC_VOLUME_UP                       77
#define HARDKEYCODE_SWC_VOLUME_DOWN                     78
#define HARDKEYCODE_SWC_UP                              80
#define HARDKEYCODE_SWC_DOWN                            81
#define HARDKEYCODE_SWC_VOLUME_BUTTON                   82
#define HARDKEYCODE_SWC_ARROW_A_UP                      83
#define HARDKEYCODE_SWC_ARROW_A_DOWN                    84
#define HARDKEYCODE_SWC_ARROW_B_UP                      85
#define HARDKEYCODE_SWC_ARROW_B_DOWN                    86
#define HARDKEYCODE_SWC_INIT                            87
#define HARDKEYCODE_HMI_BASE_1                          88
#define HARDKEYCODE_HMI_BASE_2                          89
#define HARDKEYCODE_HMI_BASE_3                          90
#define HARDKEYCODE_HMI_BASE_4                          91
#define HARDKEYCODE_HMI_BASE_5                          92
#define HARDKEYCODE_HMI_BASE_6                          93
#define HARDKEYCODE_HMI_BASE_7                          94
#define HARDKEYCODE_HMI_BASE_8                          95
#define HARDKEYCODE_JOYSTICK_UP                         150
#define HARDKEYCODE_JOYSTICK_DOWN                       151
#define HARDKEYCODE_JOYSTICK_LEFT                       152
#define HARDKEYCODE_JOYSTICK_RIGHT                      153
#define HARDKEYCODE_JOYSTICK_UPPER_LEFT                 154
#define HARDKEYCODE_JOYSTICK_UPPER_RIGHT                155
#define HARDKEYCODE_JOYSTICK_LOWER_LEFT                 156
#define HARDKEYCODE_JOYSTICK_LOWER_RIGHT                157
#define HARDKEYCODE_JOYSTICK_ENTER                      158
#define HARDKEYCODE_VDKBD_IPNFGSIF_SWC_KEY_CODE_250     250
#define HARDKEYCODE_VDKBD_IPNFGSIF_SWC_KEY_CODE_251     251
#define HARDKEYCODE_VDKBD_IPNFGSIF_SWC_KEY_CODE_252     252
#define HARDKEYCODE_HK_KEY_CODE_INVALID                 65535
#endif // KEYMAPPING_H
